- name: Install sudo
  apt:
    name: sudo
    state: present
    update_cache: true

- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Install passlib
  pip:
    name: passlib
