- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Install setcap/getcap tools
  apt:
    name: libcap2-bin
    state: present
    update_cache: true

- name: Allow nginx to bind to privileged ports
  community.general.capabilities:
    path: /usr/sbin/nginx
    capability: cap_net_bind_service=+ep
    state: present

- name: Start Nginx
  systemd:
    name: nginx
    enabled: true
    state: started

- name: Create htpasswd
  htpasswd:
    path: /etc/nginx/htpasswd
    name: treason
    password: "{{nginx_passwd}}"
    owner: www-data
    group: www-data
    mode: 0640
  notify:
    - Reload Nginx

- name: Add nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
  notify:
    - Reload Nginx
 